# Generated by Django 5.0.3 on 2024-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_post_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(max_length=300),
        ),
    ]
