services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django_network

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py makemigrations
             python manage.py migrate &&
             gunicorn --bind :8000 --workers 2 textly.wsgi"
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - media:/code/media
    networks:
      - django_network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - django_network

volumes:
  postgres_data:
  media:


networks:
  django_network:
    driver: bridge
